### PR TITLE
Spellings

### PR DESCRIPTION
**Pull request by jameshartt**
My apologies for a really nit picky PR that doesn't really add value, this it really just an opportunity for me to say thank you for creating a really helpful utility and I hope to jump on it properly in the near future. :-)

### CODE REVIEW

**Comment by marmelroy** [comment]
Thanks for noticing that James. Oops. I'll merge and update the test too so Travis is happy.

**Comment by jameshartt** [comment]
Ahhh yes, I forgot about wee Travis. Good work :-)

**Comment by jameshartt** [comment]
I should have had a look at the examples project, didn't notice the tests there :-)

**Comment by marmelroy** [comment]
No worries. I'll probably move most of the tests to the main project in the next release anyway....

**Pull request merged**
